// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lib/api/metadata_rpc_api.proto

package api

import (
	context "context"
	fmt "fmt"
	common "github.com/RosettaFlow/Carrier-Go/lib/common"
	types "github.com/RosettaFlow/Carrier-Go/lib/types"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//  ------------------------  metadata  ------------------------
type GetMetaDataDetailRequest struct {
	IdentityId           string   `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	MetadataId           string   `protobuf:"bytes,2,opt,name=metadata_id,json=metadataId,proto3" json:"metadata_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMetaDataDetailRequest) Reset()         { *m = GetMetaDataDetailRequest{} }
func (m *GetMetaDataDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetMetaDataDetailRequest) ProtoMessage()    {}
func (*GetMetaDataDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac620a9256b640e4, []int{0}
}
func (m *GetMetaDataDetailRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetMetaDataDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetMetaDataDetailRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetMetaDataDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetaDataDetailRequest.Merge(m, src)
}
func (m *GetMetaDataDetailRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetMetaDataDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetaDataDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetaDataDetailRequest proto.InternalMessageInfo

func (m *GetMetaDataDetailRequest) GetIdentityId() string {
	if m != nil {
		return m.IdentityId
	}
	return ""
}

func (m *GetMetaDataDetailRequest) GetMetadataId() string {
	if m != nil {
		return m.MetadataId
	}
	return ""
}

type GetMetaDataDetailResponse struct {
	Owner                *common.Organization  `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Information          *types.MetadataDetail `protobuf:"bytes,2,opt,name=information,proto3" json:"information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetMetaDataDetailResponse) Reset()         { *m = GetMetaDataDetailResponse{} }
func (m *GetMetaDataDetailResponse) String() string { return proto.CompactTextString(m) }
func (*GetMetaDataDetailResponse) ProtoMessage()    {}
func (*GetMetaDataDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac620a9256b640e4, []int{1}
}
func (m *GetMetaDataDetailResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetMetaDataDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetMetaDataDetailResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetMetaDataDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetaDataDetailResponse.Merge(m, src)
}
func (m *GetMetaDataDetailResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetMetaDataDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetaDataDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetaDataDetailResponse proto.InternalMessageInfo

func (m *GetMetaDataDetailResponse) GetOwner() *common.Organization {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *GetMetaDataDetailResponse) GetInformation() *types.MetadataDetail {
	if m != nil {
		return m.Information
	}
	return nil
}

type PublishMetaDataRequest struct {
	Information          *types.MetadataDetail `protobuf:"bytes,1,opt,name=information,proto3" json:"information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PublishMetaDataRequest) Reset()         { *m = PublishMetaDataRequest{} }
func (m *PublishMetaDataRequest) String() string { return proto.CompactTextString(m) }
func (*PublishMetaDataRequest) ProtoMessage()    {}
func (*PublishMetaDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac620a9256b640e4, []int{2}
}
func (m *PublishMetaDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PublishMetaDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PublishMetaDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PublishMetaDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMetaDataRequest.Merge(m, src)
}
func (m *PublishMetaDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *PublishMetaDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMetaDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMetaDataRequest proto.InternalMessageInfo

func (m *PublishMetaDataRequest) GetInformation() *types.MetadataDetail {
	if m != nil {
		return m.Information
	}
	return nil
}

type PublishMetaDataResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MetaDataId           string   `protobuf:"bytes,3,opt,name=meta_data_id,json=metaDataId,proto3" json:"meta_data_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishMetaDataResponse) Reset()         { *m = PublishMetaDataResponse{} }
func (m *PublishMetaDataResponse) String() string { return proto.CompactTextString(m) }
func (*PublishMetaDataResponse) ProtoMessage()    {}
func (*PublishMetaDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac620a9256b640e4, []int{3}
}
func (m *PublishMetaDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PublishMetaDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PublishMetaDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PublishMetaDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMetaDataResponse.Merge(m, src)
}
func (m *PublishMetaDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *PublishMetaDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMetaDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMetaDataResponse proto.InternalMessageInfo

func (m *PublishMetaDataResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PublishMetaDataResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PublishMetaDataResponse) GetMetaDataId() string {
	if m != nil {
		return m.MetaDataId
	}
	return ""
}

type RevokeMetaDataRequest struct {
	MetaDataId           string   `protobuf:"bytes,1,opt,name=meta_data_id,json=metaDataId,proto3" json:"meta_data_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeMetaDataRequest) Reset()         { *m = RevokeMetaDataRequest{} }
func (m *RevokeMetaDataRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeMetaDataRequest) ProtoMessage()    {}
func (*RevokeMetaDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac620a9256b640e4, []int{4}
}
func (m *RevokeMetaDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RevokeMetaDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RevokeMetaDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RevokeMetaDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeMetaDataRequest.Merge(m, src)
}
func (m *RevokeMetaDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *RevokeMetaDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeMetaDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeMetaDataRequest proto.InternalMessageInfo

func (m *RevokeMetaDataRequest) GetMetaDataId() string {
	if m != nil {
		return m.MetaDataId
	}
	return ""
}

type GetMetaDataDetailListResponse struct {
	Status               int32                        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string                       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MetaDataList         []*GetMetaDataDetailResponse `protobuf:"bytes,3,rep,name=meta_data_list,json=metaDataList,proto3" json:"meta_data_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetMetaDataDetailListResponse) Reset()         { *m = GetMetaDataDetailListResponse{} }
func (m *GetMetaDataDetailListResponse) String() string { return proto.CompactTextString(m) }
func (*GetMetaDataDetailListResponse) ProtoMessage()    {}
func (*GetMetaDataDetailListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac620a9256b640e4, []int{5}
}
func (m *GetMetaDataDetailListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetMetaDataDetailListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetMetaDataDetailListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetMetaDataDetailListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetaDataDetailListResponse.Merge(m, src)
}
func (m *GetMetaDataDetailListResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetMetaDataDetailListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetaDataDetailListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetaDataDetailListResponse proto.InternalMessageInfo

func (m *GetMetaDataDetailListResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetMetaDataDetailListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetMetaDataDetailListResponse) GetMetaDataList() []*GetMetaDataDetailResponse {
	if m != nil {
		return m.MetaDataList
	}
	return nil
}

type GetMetaDataDetailListByOwnerRequest struct {
	IdentityId           string   `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMetaDataDetailListByOwnerRequest) Reset()         { *m = GetMetaDataDetailListByOwnerRequest{} }
func (m *GetMetaDataDetailListByOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*GetMetaDataDetailListByOwnerRequest) ProtoMessage()    {}
func (*GetMetaDataDetailListByOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac620a9256b640e4, []int{6}
}
func (m *GetMetaDataDetailListByOwnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetMetaDataDetailListByOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetMetaDataDetailListByOwnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetMetaDataDetailListByOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetaDataDetailListByOwnerRequest.Merge(m, src)
}
func (m *GetMetaDataDetailListByOwnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetMetaDataDetailListByOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetaDataDetailListByOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetaDataDetailListByOwnerRequest proto.InternalMessageInfo

func (m *GetMetaDataDetailListByOwnerRequest) GetIdentityId() string {
	if m != nil {
		return m.IdentityId
	}
	return ""
}

func init() {
	proto.RegisterType((*GetMetaDataDetailRequest)(nil), "rpcapi.GetMetaDataDetailRequest")
	proto.RegisterType((*GetMetaDataDetailResponse)(nil), "rpcapi.GetMetaDataDetailResponse")
	proto.RegisterType((*PublishMetaDataRequest)(nil), "rpcapi.PublishMetaDataRequest")
	proto.RegisterType((*PublishMetaDataResponse)(nil), "rpcapi.PublishMetaDataResponse")
	proto.RegisterType((*RevokeMetaDataRequest)(nil), "rpcapi.RevokeMetaDataRequest")
	proto.RegisterType((*GetMetaDataDetailListResponse)(nil), "rpcapi.GetMetaDataDetailListResponse")
	proto.RegisterType((*GetMetaDataDetailListByOwnerRequest)(nil), "rpcapi.GetMetaDataDetailListByOwnerRequest")
}

func init() { proto.RegisterFile("lib/api/metadata_rpc_api.proto", fileDescriptor_ac620a9256b640e4) }

var fileDescriptor_ac620a9256b640e4 = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xd1, 0x6e, 0xd3, 0x3c,
	0x14, 0x96, 0x57, 0x6d, 0xd2, 0xef, 0x4e, 0xdb, 0x8f, 0xa5, 0x8e, 0x2e, 0xeb, 0xb2, 0x2c, 0x30,
	0x18, 0x9b, 0x48, 0xa0, 0x5c, 0x4c, 0xec, 0x72, 0x8c, 0x4d, 0x93, 0x98, 0x06, 0xd9, 0x1d, 0x42,
	0xaa, 0x9c, 0xc4, 0xeb, 0x2c, 0x92, 0x38, 0xc4, 0x4e, 0xa7, 0x02, 0x17, 0x88, 0x0b, 0x1e, 0x00,
	0x1e, 0x80, 0x5b, 0x1e, 0x85, 0x4b, 0x24, 0x5e, 0x00, 0x55, 0x3c, 0x08, 0xb2, 0x93, 0xb4, 0x6b,
	0x9b, 0x96, 0x8a, 0xbb, 0xda, 0xe7, 0xf8, 0xfb, 0xbe, 0xf3, 0x9d, 0x73, 0x1a, 0xa8, 0x07, 0xd4,
	0xb5, 0x71, 0x4c, 0xed, 0x90, 0x08, 0xec, 0x63, 0x81, 0x5b, 0x49, 0xec, 0xb5, 0x70, 0x4c, 0xad,
	0x38, 0x61, 0x82, 0xa1, 0x85, 0x24, 0xf6, 0x70, 0x4c, 0xb5, 0x9a, 0xcc, 0xf3, 0x58, 0x18, 0xb2,
	0xc8, 0x76, 0x31, 0x27, 0x59, 0x58, 0xab, 0xcb, 0x6b, 0xd1, 0x8d, 0x09, 0xef, 0x03, 0xe4, 0x91,
	0x46, 0x9b, 0xb1, 0x76, 0x40, 0x14, 0x36, 0x8e, 0x22, 0x26, 0xb0, 0xa0, 0x2c, 0xe2, 0x79, 0x74,
	0x2d, 0x8f, 0xaa, 0x93, 0x9b, 0x5e, 0xd8, 0x24, 0x8c, 0x45, 0x37, 0x0b, 0x9a, 0xaf, 0x60, 0xfd,
	0x98, 0x88, 0x53, 0x22, 0xf0, 0x21, 0x16, 0xf8, 0x90, 0x08, 0x4c, 0x03, 0x87, 0xbc, 0x49, 0x09,
	0x17, 0x68, 0x03, 0x56, 0xa9, 0x4f, 0x22, 0x41, 0x45, 0xb7, 0x45, 0xfd, 0x3a, 0x30, 0xc0, 0xf6,
	0x7f, 0x0e, 0x2c, 0xae, 0x4e, 0x7c, 0x99, 0xd0, 0x2f, 0x85, 0xfa, 0xf5, 0xb9, 0x2c, 0xa1, 0xb8,
	0x3a, 0xf1, 0xcd, 0x4f, 0x00, 0xae, 0x96, 0xc0, 0xf3, 0x98, 0x45, 0x9c, 0xa0, 0x07, 0x70, 0x9e,
	0x5d, 0x45, 0x24, 0x51, 0xc8, 0xd5, 0xa6, 0x66, 0xf5, 0xad, 0x70, 0xd3, 0x0b, 0xeb, 0x2c, 0x69,
	0xe3, 0x88, 0xbe, 0x55, 0xa5, 0x38, 0x59, 0x22, 0xda, 0x83, 0x55, 0x1a, 0x5d, 0xb0, 0x24, 0x54,
	0xb7, 0x8a, 0xb0, 0xda, 0xac, 0x59, 0xca, 0x14, 0xeb, 0x34, 0xe7, 0xcd, 0x59, 0xae, 0x67, 0x9a,
	0x2f, 0xe0, 0xca, 0xf3, 0xd4, 0x0d, 0x28, 0xbf, 0x2c, 0xb4, 0x14, 0x45, 0x8e, 0x40, 0x82, 0x99,
	0x21, 0x09, 0xbc, 0x39, 0x06, 0x99, 0x17, 0xb6, 0x02, 0x17, 0xb8, 0xc0, 0x22, 0xe5, 0x0a, 0x6e,
	0xde, 0xc9, 0x4f, 0xe8, 0x7f, 0x58, 0x09, 0x79, 0x3b, 0xf7, 0x49, 0xfe, 0x44, 0x06, 0x5c, 0x94,
	0x76, 0xb5, 0x0a, 0x0b, 0x2b, 0x03, 0x0b, 0x0f, 0x33, 0x0b, 0x1f, 0xc3, 0x9a, 0x43, 0x3a, 0xec,
	0x35, 0x19, 0x15, 0x3e, 0xfa, 0x14, 0x8c, 0x3d, 0xfd, 0x0c, 0xe0, 0xfa, 0x98, 0xfb, 0xcf, 0x28,
	0x17, 0xff, 0x20, 0xf4, 0x18, 0x2e, 0x0d, 0xd8, 0x02, 0xca, 0x45, 0xbd, 0x62, 0x54, 0xb6, 0xab,
	0xcd, 0x4d, 0x2b, 0x1b, 0x5a, 0x6b, 0x62, 0x9b, 0x9d, 0xc5, 0x42, 0x92, 0xa4, 0x36, 0x8f, 0xe0,
	0xad, 0x52, 0x4d, 0x07, 0xdd, 0x33, 0xd9, 0xe2, 0x59, 0x67, 0xaf, 0xf9, 0x6d, 0x1e, 0x2e, 0x17,
	0x28, 0xe7, 0x24, 0xe9, 0x50, 0x8f, 0xa0, 0x0f, 0x00, 0xde, 0x18, 0x03, 0x47, 0xc6, 0x14, 0x89,
	0x8a, 0x4c, 0xfb, 0x7b, 0x11, 0xe6, 0x9d, 0x8f, 0x3f, 0x7f, 0x7f, 0x99, 0x33, 0xcc, 0x35, 0xdb,
	0xc3, 0x49, 0x42, 0x49, 0x62, 0x77, 0x1e, 0xf6, 0xd7, 0xd0, 0xf6, 0x55, 0xf2, 0x3e, 0xd8, 0x41,
	0xef, 0x61, 0xad, 0xb4, 0x3c, 0xb4, 0x62, 0x65, 0x6b, 0x38, 0x18, 0xf0, 0xa7, 0x72, 0x0d, 0xb5,
	0xad, 0x89, 0xdc, 0xd7, 0x3b, 0x65, 0xde, 0x56, 0xfc, 0xba, 0xb9, 0x5a, 0xca, 0x2f, 0x1b, 0x22,
	0xd9, 0xbf, 0x02, 0xd8, 0x98, 0xe6, 0x2e, 0xda, 0x9d, 0xca, 0x36, 0xdc, 0x83, 0x59, 0xa5, 0xed,
	0x2a, 0x69, 0x5b, 0xa6, 0x31, 0x51, 0x5a, 0x8e, 0x2b, 0x15, 0xbe, 0x83, 0xcb, 0x23, 0x5b, 0x83,
	0xf4, 0x82, 0xa6, 0x7c, 0x43, 0xb5, 0x8d, 0x89, 0xf1, 0x5c, 0xc0, 0x5d, 0x25, 0x60, 0xd3, 0x6c,
	0x94, 0x0a, 0x88, 0xb3, 0x57, 0x92, 0x3c, 0x85, 0x4b, 0xc3, 0xbb, 0x84, 0xd6, 0x0b, 0xec, 0xd2,
	0x1d, 0xd3, 0x1a, 0xc3, 0x7f, 0x49, 0xe7, 0x34, 0x8c, 0x03, 0x32, 0xe3, 0x4c, 0x24, 0x0a, 0x71,
	0x1f, 0xec, 0x1c, 0xec, 0x7d, 0xef, 0xe9, 0xe0, 0x47, 0x4f, 0x07, 0xbf, 0x7a, 0x3a, 0x78, 0x79,
	0xaf, 0x4d, 0xc5, 0x65, 0xea, 0x5a, 0x1e, 0x0b, 0x6d, 0x87, 0x71, 0x22, 0x04, 0x3e, 0x0a, 0xd8,
	0x95, 0xfd, 0x24, 0xc3, 0xb8, 0x7f, 0xcc, 0xec, 0xfc, 0x3b, 0xe1, 0x2e, 0x28, 0xe6, 0x47, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x85, 0x9c, 0x32, 0xc8, 0x39, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetaDataServiceClient is the client API for MetaDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetaDataServiceClient interface {
	// 查看单个元数据详情 (包含 列字段描述)
	GetMetaDataDetail(ctx context.Context, in *GetMetaDataDetailRequest, opts ...grpc.CallOption) (*GetMetaDataDetailResponse, error)
	// 查看全网元数据列表
	GetMetaDataDetailList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMetaDataDetailListResponse, error)
	// 查看某个组织元数据列表
	GetMetaDataDetailListByOwner(ctx context.Context, in *GetMetaDataDetailListByOwnerRequest, opts ...grpc.CallOption) (*GetMetaDataDetailListResponse, error)
	// 发布元数据  (新增和编辑 都是发布新的元数据) <底层根据 原始数据Id -- OriginId 来关联 新的MetaDataId>
	PublishMetaData(ctx context.Context, in *PublishMetaDataRequest, opts ...grpc.CallOption) (*PublishMetaDataResponse, error)
	// 撤销元数据 (从底层网络撤销)
	RevokeMetaData(ctx context.Context, in *RevokeMetaDataRequest, opts ...grpc.CallOption) (*common.SimpleResponse, error)
}

type metaDataServiceClient struct {
	cc *grpc.ClientConn
}

func NewMetaDataServiceClient(cc *grpc.ClientConn) MetaDataServiceClient {
	return &metaDataServiceClient{cc}
}

func (c *metaDataServiceClient) GetMetaDataDetail(ctx context.Context, in *GetMetaDataDetailRequest, opts ...grpc.CallOption) (*GetMetaDataDetailResponse, error) {
	out := new(GetMetaDataDetailResponse)
	err := c.cc.Invoke(ctx, "/rpcapi.MetaDataService/GetMetaDataDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaDataServiceClient) GetMetaDataDetailList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMetaDataDetailListResponse, error) {
	out := new(GetMetaDataDetailListResponse)
	err := c.cc.Invoke(ctx, "/rpcapi.MetaDataService/GetMetaDataDetailList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaDataServiceClient) GetMetaDataDetailListByOwner(ctx context.Context, in *GetMetaDataDetailListByOwnerRequest, opts ...grpc.CallOption) (*GetMetaDataDetailListResponse, error) {
	out := new(GetMetaDataDetailListResponse)
	err := c.cc.Invoke(ctx, "/rpcapi.MetaDataService/GetMetaDataDetailListByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaDataServiceClient) PublishMetaData(ctx context.Context, in *PublishMetaDataRequest, opts ...grpc.CallOption) (*PublishMetaDataResponse, error) {
	out := new(PublishMetaDataResponse)
	err := c.cc.Invoke(ctx, "/rpcapi.MetaDataService/PublishMetaData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaDataServiceClient) RevokeMetaData(ctx context.Context, in *RevokeMetaDataRequest, opts ...grpc.CallOption) (*common.SimpleResponse, error) {
	out := new(common.SimpleResponse)
	err := c.cc.Invoke(ctx, "/rpcapi.MetaDataService/RevokeMetaData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaDataServiceServer is the server API for MetaDataService service.
type MetaDataServiceServer interface {
	// 查看单个元数据详情 (包含 列字段描述)
	GetMetaDataDetail(context.Context, *GetMetaDataDetailRequest) (*GetMetaDataDetailResponse, error)
	// 查看全网元数据列表
	GetMetaDataDetailList(context.Context, *emptypb.Empty) (*GetMetaDataDetailListResponse, error)
	// 查看某个组织元数据列表
	GetMetaDataDetailListByOwner(context.Context, *GetMetaDataDetailListByOwnerRequest) (*GetMetaDataDetailListResponse, error)
	// 发布元数据  (新增和编辑 都是发布新的元数据) <底层根据 原始数据Id -- OriginId 来关联 新的MetaDataId>
	PublishMetaData(context.Context, *PublishMetaDataRequest) (*PublishMetaDataResponse, error)
	// 撤销元数据 (从底层网络撤销)
	RevokeMetaData(context.Context, *RevokeMetaDataRequest) (*common.SimpleResponse, error)
}

// UnimplementedMetaDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMetaDataServiceServer struct {
}

func (*UnimplementedMetaDataServiceServer) GetMetaDataDetail(ctx context.Context, req *GetMetaDataDetailRequest) (*GetMetaDataDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetaDataDetail not implemented")
}
func (*UnimplementedMetaDataServiceServer) GetMetaDataDetailList(ctx context.Context, req *emptypb.Empty) (*GetMetaDataDetailListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetaDataDetailList not implemented")
}
func (*UnimplementedMetaDataServiceServer) GetMetaDataDetailListByOwner(ctx context.Context, req *GetMetaDataDetailListByOwnerRequest) (*GetMetaDataDetailListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetaDataDetailListByOwner not implemented")
}
func (*UnimplementedMetaDataServiceServer) PublishMetaData(ctx context.Context, req *PublishMetaDataRequest) (*PublishMetaDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMetaData not implemented")
}
func (*UnimplementedMetaDataServiceServer) RevokeMetaData(ctx context.Context, req *RevokeMetaDataRequest) (*common.SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeMetaData not implemented")
}

func RegisterMetaDataServiceServer(s *grpc.Server, srv MetaDataServiceServer) {
	s.RegisterService(&_MetaDataService_serviceDesc, srv)
}

func _MetaDataService_GetMetaDataDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetaDataDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaDataServiceServer).GetMetaDataDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcapi.MetaDataService/GetMetaDataDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaDataServiceServer).GetMetaDataDetail(ctx, req.(*GetMetaDataDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaDataService_GetMetaDataDetailList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaDataServiceServer).GetMetaDataDetailList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcapi.MetaDataService/GetMetaDataDetailList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaDataServiceServer).GetMetaDataDetailList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaDataService_GetMetaDataDetailListByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetaDataDetailListByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaDataServiceServer).GetMetaDataDetailListByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcapi.MetaDataService/GetMetaDataDetailListByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaDataServiceServer).GetMetaDataDetailListByOwner(ctx, req.(*GetMetaDataDetailListByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaDataService_PublishMetaData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMetaDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaDataServiceServer).PublishMetaData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcapi.MetaDataService/PublishMetaData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaDataServiceServer).PublishMetaData(ctx, req.(*PublishMetaDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaDataService_RevokeMetaData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeMetaDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaDataServiceServer).RevokeMetaData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcapi.MetaDataService/RevokeMetaData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaDataServiceServer).RevokeMetaData(ctx, req.(*RevokeMetaDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetaDataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcapi.MetaDataService",
	HandlerType: (*MetaDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetaDataDetail",
			Handler:    _MetaDataService_GetMetaDataDetail_Handler,
		},
		{
			MethodName: "GetMetaDataDetailList",
			Handler:    _MetaDataService_GetMetaDataDetailList_Handler,
		},
		{
			MethodName: "GetMetaDataDetailListByOwner",
			Handler:    _MetaDataService_GetMetaDataDetailListByOwner_Handler,
		},
		{
			MethodName: "PublishMetaData",
			Handler:    _MetaDataService_PublishMetaData_Handler,
		},
		{
			MethodName: "RevokeMetaData",
			Handler:    _MetaDataService_RevokeMetaData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lib/api/metadata_rpc_api.proto",
}

func (m *GetMetaDataDetailRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetMetaDataDetailRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetMetaDataDetailRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.MetadataId) > 0 {
		i -= len(m.MetadataId)
		copy(dAtA[i:], m.MetadataId)
		i = encodeVarintMetadataRpcApi(dAtA, i, uint64(len(m.MetadataId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.IdentityId) > 0 {
		i -= len(m.IdentityId)
		copy(dAtA[i:], m.IdentityId)
		i = encodeVarintMetadataRpcApi(dAtA, i, uint64(len(m.IdentityId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetMetaDataDetailResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetMetaDataDetailResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetMetaDataDetailResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Information != nil {
		{
			size, err := m.Information.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMetadataRpcApi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Owner != nil {
		{
			size, err := m.Owner.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMetadataRpcApi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PublishMetaDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PublishMetaDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PublishMetaDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Information != nil {
		{
			size, err := m.Information.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMetadataRpcApi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PublishMetaDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PublishMetaDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PublishMetaDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.MetaDataId) > 0 {
		i -= len(m.MetaDataId)
		copy(dAtA[i:], m.MetaDataId)
		i = encodeVarintMetadataRpcApi(dAtA, i, uint64(len(m.MetaDataId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Msg) > 0 {
		i -= len(m.Msg)
		copy(dAtA[i:], m.Msg)
		i = encodeVarintMetadataRpcApi(dAtA, i, uint64(len(m.Msg)))
		i--
		dAtA[i] = 0x12
	}
	if m.Status != 0 {
		i = encodeVarintMetadataRpcApi(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RevokeMetaDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RevokeMetaDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RevokeMetaDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.MetaDataId) > 0 {
		i -= len(m.MetaDataId)
		copy(dAtA[i:], m.MetaDataId)
		i = encodeVarintMetadataRpcApi(dAtA, i, uint64(len(m.MetaDataId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetMetaDataDetailListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetMetaDataDetailListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetMetaDataDetailListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.MetaDataList) > 0 {
		for iNdEx := len(m.MetaDataList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MetaDataList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMetadataRpcApi(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Msg) > 0 {
		i -= len(m.Msg)
		copy(dAtA[i:], m.Msg)
		i = encodeVarintMetadataRpcApi(dAtA, i, uint64(len(m.Msg)))
		i--
		dAtA[i] = 0x12
	}
	if m.Status != 0 {
		i = encodeVarintMetadataRpcApi(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetMetaDataDetailListByOwnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetMetaDataDetailListByOwnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetMetaDataDetailListByOwnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.IdentityId) > 0 {
		i -= len(m.IdentityId)
		copy(dAtA[i:], m.IdentityId)
		i = encodeVarintMetadataRpcApi(dAtA, i, uint64(len(m.IdentityId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMetadataRpcApi(dAtA []byte, offset int, v uint64) int {
	offset -= sovMetadataRpcApi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetMetaDataDetailRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IdentityId)
	if l > 0 {
		n += 1 + l + sovMetadataRpcApi(uint64(l))
	}
	l = len(m.MetadataId)
	if l > 0 {
		n += 1 + l + sovMetadataRpcApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetMetaDataDetailResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Owner != nil {
		l = m.Owner.Size()
		n += 1 + l + sovMetadataRpcApi(uint64(l))
	}
	if m.Information != nil {
		l = m.Information.Size()
		n += 1 + l + sovMetadataRpcApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PublishMetaDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Information != nil {
		l = m.Information.Size()
		n += 1 + l + sovMetadataRpcApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PublishMetaDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovMetadataRpcApi(uint64(m.Status))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovMetadataRpcApi(uint64(l))
	}
	l = len(m.MetaDataId)
	if l > 0 {
		n += 1 + l + sovMetadataRpcApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RevokeMetaDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MetaDataId)
	if l > 0 {
		n += 1 + l + sovMetadataRpcApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetMetaDataDetailListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovMetadataRpcApi(uint64(m.Status))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovMetadataRpcApi(uint64(l))
	}
	if len(m.MetaDataList) > 0 {
		for _, e := range m.MetaDataList {
			l = e.Size()
			n += 1 + l + sovMetadataRpcApi(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetMetaDataDetailListByOwnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IdentityId)
	if l > 0 {
		n += 1 + l + sovMetadataRpcApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovMetadataRpcApi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMetadataRpcApi(x uint64) (n int) {
	return sovMetadataRpcApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetMetaDataDetailRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadataRpcApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetMetaDataDetailRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetMetaDataDetailRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentityId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IdentityId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadataRpcApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetMetaDataDetailResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadataRpcApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetMetaDataDetailResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetMetaDataDetailResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Owner == nil {
				m.Owner = &common.Organization{}
			}
			if err := m.Owner.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Information", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Information == nil {
				m.Information = &types.MetadataDetail{}
			}
			if err := m.Information.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadataRpcApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PublishMetaDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadataRpcApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PublishMetaDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PublishMetaDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Information", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Information == nil {
				m.Information = &types.MetadataDetail{}
			}
			if err := m.Information.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadataRpcApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PublishMetaDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadataRpcApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PublishMetaDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PublishMetaDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetaDataId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetaDataId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadataRpcApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RevokeMetaDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadataRpcApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RevokeMetaDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RevokeMetaDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetaDataId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetaDataId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadataRpcApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetMetaDataDetailListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadataRpcApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetMetaDataDetailListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetMetaDataDetailListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetaDataList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetaDataList = append(m.MetaDataList, &GetMetaDataDetailResponse{})
			if err := m.MetaDataList[len(m.MetaDataList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadataRpcApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetMetaDataDetailListByOwnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadataRpcApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetMetaDataDetailListByOwnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetMetaDataDetailListByOwnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentityId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IdentityId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadataRpcApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetadataRpcApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMetadataRpcApi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMetadataRpcApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetadataRpcApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMetadataRpcApi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMetadataRpcApi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMetadataRpcApi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMetadataRpcApi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetadataRpcApi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMetadataRpcApi = fmt.Errorf("proto: unexpected end of group")
)
